# Generated by Django 5.2.6 on 2025-12-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0023_payroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='is_compensated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='medical_proof',
            field=models.FileField(blank=True, null=True, upload_to='medical_proofs/'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('CL', 'Casual Leave'), ('ML', 'Medical Leave'), ('EL', 'Emergency Leave')], max_length=3),
        ),
    ]
