# Generated by Django 5.2.6 on 2025-12-19 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0025_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
