# Generated by Django 5.2.6 on 2026-01-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0029_alter_employee_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='year',
            field=models.IntegerField(default=2026),
        ),
    ]
