# Generated by Django 5.2.1 on 2026-04-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0032_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
    ]
