# Generated by Django 5.2.1 on 2026-04-13 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_app', '0033_leaverequest_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='is_paid',
        ),
    ]
